VERSION="0.0.1"
DAO_NAME="Test DAO"
DAO_DESCRIPTION="A DAO for testing stuff"
DAO_OFFICIAL_EMAIL="hi@testdao.org"
DAO_URL="https://testdao.org"
DAO_VOTING_TOKEN="GOV:GBNOMH3B6BIQE65TZVVBNOCTMLN7MYORU5GX6YNBX5YBGCI45R2EMGOV"
MIN_VOTING_POWER_CREATE_PROPOSAL="100"
MIN_VOTING_POWER_CREATE_QUORUM="40000"
MIN_VOTING_DURATION_SECONDS="300"
OFFER_AMMOUNT_PER_VOTING_OPTION="100000000000"
PROPOSAL_ACCOUNT_RESCUE_SIGNERS=[
"GCBY2B7KKVE4T66B4ZECNLOYT3Y772GHJTATP33IDUSYXTZSJNNYRWX5",
"GAA72JLMNMAIZ44XYYNKACANN6THCU7MLKB4M3YDFOHI4IEU4PLTDLLY",
"GDUGCQEZ5XOCZ6MDXI44ZALD4GDJBHE6XZAXPRB7DTGJ6O2S76VG7FML"
]
DAO_PUBLIC_KEY="GAZZWLZCTLL2GMEICJWMGF4T3BDE6QTQEQDCBKJGXKUUD3D66THAGDAO"